### ISSUE TITLE
[etc] Organization Repository 복제 방법

### ISSUE THREAD

**Issue by dnwlsrla40** [h-dt/WeCo#74]
## Organization Repository 복제 방법

1. github에서 이용 방법 - https://sir.kr/pg_tip/15556
2. git 명령어 통한 방법 - https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository

**Comment by jiji-hoon96** [comment]
@dnwlsrla40  확인해서 복제완료했습니다 감사합니다!!
